# Generated by Django 5.0.8 on 2024-09-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='last_name',
        ),
    ]
