# Generated by Django 5.0.8 on 2024-09-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_recruiter_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='open_jobs',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='users.job'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='is_open_to_work',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='languages',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='skills',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
