# Generated by Django 5.0.8 on 2024-09-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_company_open_jobs_alter_talent_is_open_to_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='open_jobs',
            field=models.ManyToManyField(related_name='companies', to='users.job'),
        ),
    ]
