# Generated by Django 5.0.8 on 2024-09-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_user_type_alter_talent_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='open_jobs',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='users.job'),
        ),
    ]
