# Generated by Django 5.0.8 on 2024-09-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_company_open_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
