# Generated by Django 5.0.8 on 2024-09-05 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_recruiter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(default='a86619c7-8728-4dd1-83b4-da460fa46fda', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.recruiter'),
            preserve_default=False,
        ),
    ]
