# Generated by Django 4.2.7 on 2024-09-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_job_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='languages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
