# Generated by Django 4.2.7 on 2024-09-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_talent_languages_alter_talent_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='divisions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
