# Generated by Django 4.2.7 on 2024-10-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_location_job_city_job_residence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='residence',
        ),
    ]
