# Generated by Django 4.2.7 on 2024-10-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_recruiter_recommendation_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='recommendation_letter',
            new_name='profile_picture',
        ),
    ]
