# Generated by Django 4.2.7 on 2024-10-03 20:58

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_rename_recommendation_letter_recruiter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.recommendation_letter_upload_path),
        ),
    ]
