# Generated by Django 4.2.7 on 2024-10-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_recruiter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='notified_jobs',
            field=models.ManyToManyField(blank=True, related_name='notified_talents', to='users.job'),
        ),
    ]
