# Generated by Django 4.2.7 on 2024-10-04 15:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_talent_notified_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_picture_upload_path),
        ),
    ]
