# Generated by Django 4.2.7 on 2024-10-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_recruiter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='newsletter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
