# Generated by Django 4.2.7 on 2024-10-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_talent_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
