# Generated by Django 4.2.7 on 2024-10-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_recruiter_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
