# Generated by Django 4.2.7 on 2024-10-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_talent_desired_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='field_of_interest',
        ),
    ]
