# Generated by Django 4.2.7 on 2024-11-14 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_talent_field_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
