# Generated by Django 5.0.8 on 2024-09-05 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('users', '0010_recruiter_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_conversations', to='users.recruiter'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_conversations', to='users.talent'),
        ),
    ]
