# Generated by Django 4.2.7 on 2024-10-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0026_remove_talent_notified_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.job')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.talent')),
            ],
            options={
                'unique_together': {('talent', 'job')},
            },
        ),
    ]
